name: Deploy CodeSphere API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Oracle Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/codesphere-api
            ./deploy.sh